import { DEFAULT_THEME } from '@styling/default.theme'
import StyledComponentsRegistry from '@styling/registry'
import type { Metadata } from 'next'
import { ThemeProvider } from 'styled-components'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <StyledComponentsRegistry>
                    <ThemeProvider theme={DEFAULT_THEME}>
                        {children}
                    </ThemeProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}
